export const CatchAsyncError = (func) => (request, response, next) => {
};
